#!/usr/bin/env ruby
# frozen_string_literal: true

# 前提
# ・ファイルの末尾はコメント行や空行ではない

require_relative 'lib/code_writer'
require_relative 'lib/parser'

class VMTranslator
  def initialize(path)
    @parser = Parser.new(path)
    @file_name = path.sub(/\.vm$/, '.asm') # 出力するファイル名を取得
    @code_writer = CodeWriter.new(@file_name)
  end

  def execute
    while @parser.has_more_lines?
      @parser.advance
      case @parser.command_type
      in :c_arithmetic
        # add
        # arg1 = :add
        command = @parser.arg1
        @code_writer.write_arithmetic(command)
      in :c_push | :c_pop
        # push constant 1
        # arg1 = :constant
        # arg2 = 1
        command = @parser.command_type
        segment = @parser.arg1
        index = @parser.arg2
        @code_writer.write_push_pop(command, segment, index)
      end
    end
    @code_writer.close
  end
end

if __FILE__ == $PROGRAM_NAME
  VMTranslator.new(ARGV[0]).execute
end
