#!/usr/bin/env ruby
# frozen_string_literal: true

# 前提
# ・ファイルの末尾はコメント行や空行ではない

class VMTranslator
  def initialize(path)
    @parser = Parser.new(path)
    @file_name = path.sub(/\.vm$/, '.asm') # 出力するファイル名を取得
    @code_writer = CodeWriter.new(@file_name)
  end

  def execute
    while @parser.has_more_lines?
      @parser.advance
      case @parser.command_type
      in :c_arithmetic
        # add
        # arg1 = :add
        command = @parser.arg1
        @code_writer.write_arithmetic(command)
      in :c_push
        # push constant 1
        # arg1 = :constant
        # arg2 = 1
        segment = @parser.arg1
        index = @parser.arg2
        @code_writer.write_push_pop(:push, segment, index)
      end
    end
    @code_writer.close
  end
end

class Parser
  def initialize(path)
    @lines = File.open(path, "r").readlines
    @index = -1
  end

  def has_more_lines?
    # 5行あるとして、@indexは0~4まで
    @lines.length > @index + 1
  end

  def advance
    # ループを回して空行、コメントじゃない行を探す
    while has_more_lines?
      @index += 1
      is_comment = current_line.start_with?('//')
      is_blank = current_line.empty?
      break if !is_comment && !is_blank
    end
  end

  def command_type
    tmp = current_line.split[0]
    case tmp
    when 'push'
      :c_push
    when 'add'
      :c_arithmetic
    end
  end

  def arg1
    # 1
    # push constant 1
    # => constant
    # 2
    # add
    # => add
    if (command_type == :c_arithmetic)
      return current_line
    end
    args = current_line.split
    args[1]
  end

  def arg2
    # push constant 1
    # => 1
    args = current_line.split
    args[2]
  end

  private

  def current_line
    @lines[@index].strip
  end
end

class CodeWriter
  def initialize(file_name)
    @file_name = file_name
    @file = File.open(@file_name, "w", 0755)
    # asm = <<~ASM
    #   @256
    #   D=A
    #   @SP
    #   M=D
    # ASM
    # @file.print(asm)
  end

  def close
    asm = <<~ASM
      (END)
      @END
      0;JMP
    ASM
    @file.print(asm)
    @file.close
  end

  def write_arithmetic(command)
    asm = <<~ASM
      @SP
      A=M-1
      D=M
      A=A-1
      M=D+M
      @SP
      M=M-1
    ASM
    @file.print(asm)
  end

  def write_push_pop(command, segment, index)
    asm = <<~ASM
      @#{index}
      D=A
      @SP
      A=M
      M=D
      @SP
      M=M+1
    ASM
    @file.print(asm)
  end
end

if __FILE__ == $PROGRAM_NAME
  VMTranslator.new(ARGV[0]).execute
end
